# site
# --- editar y ajustar de acuerdo al curso 
site_name: Nombre del Curso UNSAM
site_description: "Sitio Web del Curso"
site_author: "Nombre Apellido"
#site_url: https://curso.unsam.edu.ar

# repository
# --- si el sitio está alojado en un repo, describirlo acá 
repo_name: 'cursos-unsam-mkdocs-template'
repo_url: https://github.com/trypanosomatics/cursos-unsam-mkdocs-template

# theme 
# --- customizar apariencia editando palette 
# --- consultar https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
theme:
  name: material
  language: es 
  features:
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.tabs
    - navigation.indexes
  palette: 
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch 
        name: Cambiar a modo oscuro
    - scheme: slate 
      primary: indigo
      accent: indigo
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo claro

# plugins
plugins:
  - search
  - mkdocs-video 
  - awesome-pages
  #- git-revision-date
  - tags:
      tags_file: tags.md 

# markdown extensions
markdown_extensions:
  - meta
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji

# extra
# --- editar los URLs, agregar los links especificos a cada cuenta, canal, etc. 
# --- reordenar los bloques de iconos + links de acuerdo al gusto
extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://workspace-name.slack.com
    - icon: fontawesome/brands/github
      link: https://github.com/repo/name
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cuenta
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/channel/channel-id
    - icon: fontawesome/brands/discord
      link: https://discord.com/server

# extra++
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

# copyright
# --- editar y ajustar de acuerdo al curso
copyright: Copyright &copy; 2022 Area Bioinformatica UNSAM  
